apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: workflow360
data:
  01-create-databases.sql: |
    CREATE DATABASE postgres_timecard;
    CREATE DATABASE postgres_expense;
    CREATE DATABASE postgres_invoice;
    CREATE DATABASE postgres_vms;
    CREATE DATABASE postgres_monolith;
