apiVersion: v1
kind: ConfigMap
metadata:
  name: timecard-config
  namespace: workflow360
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080

  ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=postgres_timecard;Username=postgres;Password=postgres123

  RabbitMq__HostName: rabbitmq
  RabbitMq__Port: "5672"
