version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - workflow360-postgres-data:/var/lib/postgresql/data
    networks:
      - workflow360-net

  user-service:
    image: workflow360-user-service:latest
    container_name: user-service
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - workflow360-net

volumes:
  workflow360-postgres-data:

networks:
  workflow360-net:
    driver: bridge