apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: workflow360
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres123
            # IMPORTANT: do NOT set POSTGRES_DB here
            # because we are creating multiple DBs via init SQL
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            # 🔴 THIS IS WHERE init SQL IS MOUNTED
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d

      # 🔴 THIS IS WHERE volumes ARE DECLARED
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi