name: Deploy to QA

on:
  workflow_dispatch:   # manual button

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.QA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.QA_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to QA server
        run: |
          ssh ${{ secrets.QA_USER }}@${{ secrets.QA_HOST }} "
            cd D:/github/WorkFlow360 &&
            bash deploy.sh
          "