name: TimecardServiceRelease

on:
  push:
    branches:
      - main
    paths:
      - "services/timecard-service/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy image to Kubernetes
        run: |
          kubectl set image deployment/timecard-service \
          timecard-service=ojasteredesai/timecard-service:${{ github.sha }} \
          -n workflow360

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/timecard-service -n workflow360
