name: Timecard Service – CI

on:
  push:
    paths:
      - "services/timecard-service/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ojasteredesai/timecard-service:${{ github.sha }} ./services/timecard-service

      - name: Push Docker image
        run: |
          docker push ojasteredesai/timecard-service:${{ github.sha }}
