name: User Service – CI

on:
  push:
    paths:
      - "services/user-service/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (validation only)
        run: |
          docker build \
            -t user-service-ci:${{ github.sha }} \
            services/user-service
