name: Build User Service Image

on:
  push:
    paths:
      - "services/user-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ojasteredesai/user-service:${{ github.sha }} services/user-service

      - name: Push Docker image
        run: docker push ojasteredesai/user-service:${{ github.sha }}