name: User Service – Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version & SHA
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          SHORT_SHA=$(git rev-parse --short HEAD)

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SHA_TAG=sha-$SHORT_SHA" >> $GITHUB_ENV

      - name: Login to Registry
        run: docker login \
          -u ${{ secrets.DOCKER_USERNAME }} \
          -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & tag image
        run: |
          IMAGE=${{ secrets.DOCKER_NAMESPACE }}/user-service

          docker build -t $IMAGE:${{ env.VERSION }} services/user-service
          docker tag  $IMAGE:${{ env.VERSION }} $IMAGE:${{ env.SHA_TAG }}
          docker tag  $IMAGE:${{ env.VERSION }} $IMAGE:latest

      - name: Push image
        run: |
          IMAGE=${{ secrets.DOCKER_NAMESPACE }}/user-service

          docker push $IMAGE:${{ env.VERSION }}
          docker push $IMAGE:${{ env.SHA_TAG }}
          docker push $IMAGE:latest